# Generated by Django 3.2.6 on 2021-08-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamii', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exporter',
            name='category',
        ),
        migrations.RemoveField(
            model_name='exporter',
            name='importer',
        ),
    ]
