# Generated by Django 3.2.6 on 2021-08-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamii', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
