# Generated by Django 3.2.6 on 2021-08-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamii', '0002_auto_20210826_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
