# Generated by Django 3.2.6 on 2021-08-25 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamii', '0003_auto_20210825_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('year', models.IntegerField()),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamii.exporter')),
            ],
        ),
        migrations.CreateModel(
            name='SubIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='importer',
            name='exporter',
        ),
        migrations.RemoveField(
            model_name='importer',
            name='tv',
        ),
        migrations.RemoveField(
            model_name='importer',
            name='year',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.AddField(
            model_name='industry',
            name='importer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamii.importer'),
        ),
        migrations.AddField(
            model_name='industry',
            name='sub_industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamii.subindustry'),
        ),
    ]
