# Generated by Django 3.2.6 on 2021-08-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamii', '0003_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('meaning', models.TextField(null=True)),
            ],
        ),
    ]
