# Generated by Django 3.2.6 on 2021-08-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamii', '0004_auto_20210825_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporter',
            name='gdp',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='industry',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='subindustry',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
