# Generated by Django 3.2.6 on 2021-08-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamii', '0007_profile_user_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exporter',
            old_name='edb',
            new_name='Export_From_edb',
        ),
        migrations.RenameField(
            model_name='exporter',
            old_name='gdp',
            new_name='Export_From_gdp',
        ),
        migrations.RemoveField(
            model_name='exporter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='exporter',
            name='value',
        ),
        migrations.AddField(
            model_name='exporter',
            name='Export_From',
            field=models.TextField(blank=True, choices=[('RSA', 'RSA'), ('Angola', 'Angola')], max_length=500),
        ),
        migrations.AddField(
            model_name='exporter',
            name='Export_Industry',
            field=models.TextField(blank=True, choices=[('Manufacturing', 'Manufacturing'), ('Textile', 'Textile')], max_length=500),
        ),
        migrations.AddField(
            model_name='exporter',
            name='Export_To',
            field=models.TextField(blank=True, choices=[('RSA', 'RSA'), ('Angola', 'Angola')], max_length=500),
        ),
    ]
