# Generated by Django 3.2.6 on 2021-08-28 01:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamii', '0008_auto_20210827_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exporter',
            name='Export_From_edb',
        ),
        migrations.RemoveField(
            model_name='exporter',
            name='Export_From_gdp',
        ),
        migrations.AddField(
            model_name='exporter',
            name='Export_License',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='exporter',
            name='Export_Prohibitions',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='exporter',
            name='Export_Sanitary_Phytosanitary_Measures',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='exporter',
            name='Export_Taxes',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='exporter',
            name='Export_Industry',
            field=models.TextField(blank=True, choices=[('Manufacturing', 'Manufacturing'), ('Textile', 'Textile'), ('Live Animals', 'Live Animals')], max_length=500),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
