# Generated by Django 3.2.6 on 2021-08-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamii', '0011_event_event_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
