# Generated by Django 3.2.6 on 2021-08-29 20:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamii', '0014_auto_20210829_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exporter',
            old_name='regulator',
            new_name='Regulator',
        ),
        migrations.RenameField(
            model_name='exporter',
            old_name='regulator_contact',
            new_name='Regulator_contact',
        ),
        migrations.RemoveField(
            model_name='exporter',
            name='Export_License',
        ),
        migrations.RemoveField(
            model_name='exporter',
            name='Export_Prohibitions',
        ),
        migrations.RemoveField(
            model_name='exporter',
            name='Export_Sanitary_Phytosanitary_Measures',
        ),
        migrations.AddField(
            model_name='exporter',
            name='Export_Domestic_Requirements',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='exporter',
            name='Export_Market_Conditions',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='exporter',
            name='Export_Product_Requirements',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='exporter',
            name='Export_Tariff',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='exporter',
            name='Export_preShipment_Inspection',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
