# Generated by Django 3.2.6 on 2021-08-29 20:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamii', '0015_auto_20210829_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exporter',
            name='Regulator',
        ),
        migrations.RemoveField(
            model_name='exporter',
            name='Regulator_contact',
        ),
        migrations.AddField(
            model_name='exporter',
            name='Export_TradePartner',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
